#!/bin/bash                         #-- what is the language of this shell
#                                  #-- Any line that starts with #$ is an instruction to SGE
#$ -S /bin/bash                     #-- the shell for the job
#$ -o output_error_directory       #-- output directory (fill in)
#$ -e output_error_directory       #-- error directory (fill in)
#$ -cwd                            #-- tell the job that it should start in your working directory
#$ -r y                            #-- tell the system that if a job crashes, it should be restarted
#$ -j y                            #-- tell the system that the STDERR and STDOUT should be joined
#$ -l mem_free=1G                  #-- submits on nodes with enough free memory (required)
#$ -l arch=linux-x64               #-- SGE resources (CPU type)
#$ -l netapp=2G,scratch=2G         #-- SGE resources (home and scratch disks)
#$ -l h_rt=336:00:00               #-- runtime limit (see above; this requests 24 hours)
#$ -t 1-148                        #-- remove first '#' to specify the number of
#$ -tc 150                                   #-- tasks if desired (see Tips section)

readarray files < /pollard/home/ngarud/shattuck/metagenomic_fastq_files/Karlsson_2013/PRJEB1786_run_accessions_only.txt
files=(null ${files[@]}) # this pads the file with an extra line in the beginning. 
file=${files[$SGE_TASK_ID]}
echo $file

dir='/pollard/home/ngarud/shattuck/metagenomic_fastq_files/Karlsson_2013/fastq_files_no_adapter'

skewer -m any -t 8 -k 20 -x ~/deep_learning_microbiome/adapters/all_adapters_R1.fa -y ~/deep_learning_microbiome/adapters/all_adapters_R2.fa ${dir}/${file}_1.fastq.gz ${dir}/${file}_2.fastq.gz -o ~/shattuck/metagenomic_fastq_files/Karlsson_2013/fastq_files_no_adapter/${file}
